### ISSUE TITLE
'loss_rpn_loc': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>) 

### ISSUE THREAD

**Issue by hehew321** [vincrichard/EfficientPS#5]
在训练的时候出现'loss_rpn_loc': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>) ，没找到哪里的问题

**Comment by vincrichard** [comment]
I am sorry but I don't speak Chinese and you will need to provide more detail for me to have a chance of understanding what's going on. I haven't touch this repository in a while.

**Comment by vincrichard** [comment]
closing the issue for now
