### ISSUE TITLE
Training custom dataset in colab

### ISSUE THREAD

**Issue by cspearl** [vincrichard/EfficientPS#6]
Hi, I tried running the official code of EfficientPS(from their github) on google colab but because of restricted cuda, pytorch versions and versions of other dependencies too, I kept facing errors.
Then I came across your implementation. And while setting up did not found any error till now. But I haven't yet tried training. I want to train another dataset (not cityscapes) . If you could please help me how should I change this code to train on a custom dataset - mainly the panoptic dataloader part.
Thanks!

**Comment by vincrichard** [comment]
Hello, the code should work, but you probably will need to create a new Dataset Class to fit the dataset you want to use. At the moment the preprocessing happening in the dataset class is fitted for cityscape (number of background class and instance to detect). You will also have to change the mean / std inside the config to fit your own dataset.
Other than this, it's been a while and I haven't tested the code without cityscape, but it should mostly work out fine.
