### ISSUE TITLE
Load pretrained model

### ISSUE THREAD

**Issue by khalishaputri18** [vincrichard/EfficientPS#8]
HI, @vincrichard thank you for this amazing work. Is there any way I can load a pre-trained model from your implementation of EfficientPS before training? Thanks a lot.

**Comment by vincrichard** [comment]
Hello @khalishaputri18, if you want to use the original weights of the authors, I don't think my code will do. The [original repo](https://github.com/DeepSceneSeg/EfficientPS) did not exist and so there are some differences between both codes. This will prevent any direct loading of the weights.

If you want to start training with the sub optimal model I trained, I shared the weights on hugging faces: https://huggingface.co/vincrichard/EfficientPS/tree/main

**Comment by khalishaputri18** [comment]
i see, thanks a lot!
